routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::resource('dossiers','DossiersController');
Route::resource('evenements', 'EvenementsController');
Route::resource('mps','MpsController');
Route::get('/folder','DossiersController@index');
Route::post('dossier/search','DossiersController@search')->name('dossiers.search');
Route::post('mp/search','MpsController@search')->name('mps.search');
Route::get('/search','DossiersController@searchFolder');
Route::get('/statistics','DossiersController@statistics');
Auth::routes();


Route::get('/mps','MpsController@index');
Route::get('/export', 'MpsController@export')->name('mps.export');
Route::get('/exportsearch', 'MpsController@exportsearch')->name('mps.exportsearch');
Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/MpsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\MpCreateRequest;
use App\Http\Requests\MpUpdateRequest;
use App\Repositories\MpRepository;
use App\Validators\MpValidator;
use App\Repositories\DivisionRepository;
use App\Http\Requests\MpSearchRequest;
use App\Criteria\SearchMpCriteria;
use App\Exports\MpsExport;
use App\Exports\SearchMpFromView;
use Maatwebsite\Excel\Facades\Excel;

/**
 * Class MpsController.
 *
 * @package namespace App\Http\Controllers;
 */
class MpsController extends Controller
{
    /**
     * @var MpRepository
     */
    protected $repository;
    protected $divisionrepo;

    /**
     * @var MpValidator
     */
    protected $validator;

    /**
     * MpsController constructor.
     *
     * @param MpRepository $repository
     * @param MpValidator $validator
     */
    public function __construct(MpRepository $repository,DivisionRepository $division, MpValidator $validator)
    {
        $this->repository = $repository;
        $this->divisionrepo=$division;
        $this->validator  = $validator;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $divisions =$this->divisionrepo->pluck('intitule','id');
        $mps = $this->repository->paginate(10);
        if (request()->wantsJson()) {

            return response()->json([
                'data' => $mps,
            ]);
        }

        return view('layouts.mps.index', compact('mps','divisions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  MpCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function store(MpCreateRequest $request)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);

            $mp = $this->repository->create($request->all());

            $response = [
                'message' => 'Mp crée avec succèe.',
                'data'    => $mp->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $mp = $this->repository->find($id);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $mp,
            ]);
        }

        return view('mps.show', compact('mp'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $mp = $this->repository->find($id);
        $divisions =$this->divisionrepo->pluck('intitule','id');
        return view('layouts.mps.updatemps', compact('mp','divisions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  MpUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function update(MpUpdateRequest $request, $id)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $mp = $this->repository->update($request->all(), $id);

            $response = [
                'message' => 'Effectué avec succèe.',
                'data'    => $mp->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Mp deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Mp deleted.');
    }
    public function search(MpSearchRequest $request){
        $mps = $this->repository->pushCriteria(new SearchMpCriteria($request))->paginate(8);
        return redirect()->back()->with('response', $mps);
    }

    public function create(){
        $divisions = $this->divisionrepo->pluck('acronyme','id');
        return view('layouts.mps.addmps',compact('divisions'));
    }
    public function export() 
{
    return Excel::download(new MpsExport(), 'mps.xlsx');
}

public function exportsearch() 
{
    return Excel::download(new SearchMpFromView(), 'mps.xlsx');
}
}

resources/views/layouts/mps/addmps.blade.php
@extends('layouts.app')
@section('content')               
                     
            <h3><span class="title">Ajouter une instruction</span><span class="underlined">&nbsp;</span></h3> 
                 @if (Session::get('message'))
                <div class="success">
                    {!! Session::get('message')['message'] !!}
                </div> 
                @endif
				{{ Form::open(['route' => 'mps.store']) }}
                <fieldset class="new_folder">
                <legend>Référence bureau d'ordre</legend>
    			<table>
                    <tr>
                    <td>{{Form::label('num_envoi', 'Numéro d envoi')}}</td>
                    <td> {{Form::number('num_envoi')}}</td>
                    <td>{{Form::label('date_envoie', 'Date envoi')}}</td>
                    <td> {{Form::date('date_envoie')}}</td>
                    </tr>
                    <tr>
                    <td>{{Form::label('num_arrive', 'Numéro d arrivée')}}</td>
                    <td> {{Form::number('num_arrive')}}</td>
                    <td>{{Form::label('date_arrive', 'Date arrivée')}}</td>
                    <td> {{Form::date('date_arrive')}}</td>
                    </tr>

                    <tr>
                    <td>{{Form::label('emetteur', 'Emetteur')}}</td>
                    <td> {{Form::text('emetteur')}}</td>
                    </tr>
                </table>    
                </fieldset>
                
                <table>
                </table>
                <fieldset class="new_folder">
                <legend>Référence Cabinet</legend>
                <table>
                <tr>
                <td>{{Form::label('date_visa', 'Date visa')}}</td>
                <td> {{Form::date('date_visa')}}</td>
                </tr>
                <tr>
                <td>{{Form::label('division_id', 'Division')}} </td>
                <td>{!! Form::select('division_id', 
                            $divisions, 
                            null,['placeholder' => 'Selectionnez Division..']) !!}</td>
                </tr>
                <tr>
                <td>{{Form::label('type', 'Type')}} </td>
                   <td> {!! Form::select('type', 
                            ["Instruction" => "Instruction","Requete" => "Requete","Demande audience" => "Demande audience"], 
                            null,[]) !!}</td>
                </tr>
                <tr>
                <td>{{Form::label('objet', 'Objet')}}</td>
                <td> {{Form::text('objet')}}</td>
                </tr>
                <tr>
                <td>{{Form::label('instructions', 'Instructions')}}</td>
        		<td>{{ Form::textarea('instructions') }}</td>
                </tr>
                <tr>
                <td>{{Form::label('date_limit', 'Date limite')}}</td>
                <td> {{Form::date('date_limit')}}</td>
                </tr>
                </table>
                </fieldset>
                {{Form::submit('Valider',array('class' => 'button'))}}
				{{ Form::close() }}
              


                <div class="clear"></div>
               
                @endsection

resources/views/layouts/mps/index.blade.php
@extends('layouts.app')
@section('content')
<h3><span class="title">Les instructions en instance</span><span class="underlined">&nbsp;</span></h3>
              
<a class="add fa" id="addevenement" href="{{ route('mps.create') }}" title=""> Ajouter un élément</a>
               
                {{ Form::open(['route' => 'mps.search','class'=>'searchform']) }}
                <table>
                <tr>
                <td>{{Form::label('date_limit', 'Date limit')}}</td><td> {{Form::date('date_limit')}}</td>
                <td>{{Form::label('division_id', 'Division')}} </td><td>{!! Form::select('division_id', 
                            $divisions, 
                            null,['placeholder' => 'Selectionnez Division..']) !!}</td>
                </tr>
                <tr>
                <td>{{Form::label('type', 'Type')}} </td><td>{!! Form::select('type', 
                  ["Instruction" => "Instruction","Requete" => "Requete","Demande audience" => "Demande audience"], 
                            null,['placeholder' => 'Selectionnez Type..']) !!}</td>

                <td>{{Form::label('etat', 'Etat')}} </td><td>{!! Form::select('etat', 
                  ["en cours" => "en cours","traité" => "traité"], 
                            null,['placeholder' => 'Selectionnez Etat..']) !!}</td>
                <td>{{Form::submit('Valider',array('class' => 'button'))}}</td>
                </tr>
                <br />
                </table>
                {{ Form::close() }}
               
                
                <div class="tablebox">
                  @if (Session::has('response'))
                      @if (count(Session::get('response'))===0)
                      <tr><td>Aucun élément trouvé</td></tr>
                      @else
                      @php
                       $mps = Session::get('response');
                      @endphp
                      @include('layouts.mps.searchMpTable',$mps)
                      @endif
                    @else
                  @include('layouts.mps.mptable',$mps)
                  @endif
                </div>
                <div class="clear"></div>
                @endsection

resources/views/layouts/mps/mptable.blade.php
<a href="{{route('mps.export')}}" value="Export" ><img width="50" height="50" src="img/iconeexcel.png" alt="logo"/></a>

                  <table border="1|0">
                      <thead>
                          <tr>
                            <th colspan="1" rowspan="2">Type</th>
                            <th colspan="5">Référence Bureau d'ordre</th>
                            <th colspan="5">Référence Cabinet</th>
                            <th colspan="2"></th>
                          </tr>
                          <tr>
                          <th>N° ENVOI</th>
                          <th> Date envoie</th>
                          <th> N° Arrivé</th>
                          <th>Date arrivé</th>
                          <th>Emetteur</th>

                          <th>Date VISA</th>
                          <th>Objet</th>
                          <th>Division</th>
                          <th>Instructions</th>
                          <th>date limit</th>
                          <th>Etat</th>
                          <th>Actions</th>
                          </tr>
                      </thead>
                      <tbody>
                      @foreach($mps as $mp) 
                      <tr class="row0">
                      <td>{{$mp->type}}</td>
                      <td>{{$mp->num_envoi}}</td>
                      <td>{{$mp->date_envoie}}</td>
                      <td>{{$mp->num_arrive}}</td>
                      <td>{{$mp->date_arrive}}</td>
                      <td>{{$mp->emetteur}}</td>

                      <td>{{$mp->date_visa}}</td>
                      <td>{{$mp->objet}}</td>
                      <td>{{$mp->divisionconcernee->acronyme}}</td>
                      <td>{{$mp->instructions}}</td>
                      <td>{{$mp->date_limit}}</td>
                      <td>{{$mp->etat}}</td>

                      <td>
                      <a  href="#" title=""><input type="button" class="fa view" value="&#xf06e;"/></a>
                      <a  href="{{ route('mps.edit',$mp->id)}}" title=""><input type="button" class="fa view" value="&#xf044;"/></a>
                      {!! Form::open(['method' => 'DELETE','route' => ['mps.destroy', $mp->id],'style'=>'display:inline','onsubmit' => 'return confirmDeletemps()']) !!}
                            <input type="submit" class="fa delete" value="&#xf1f8;" />
                      {!! Form::close() !!}
                      </td>
                      </tr>
                      @endforeach                   
                      </tbody>
                  </table>
                  <table>
                          <tr>
                              <td>                       
                              <b> Total: {{$mps->total()}} dossiers trouvés</b>
                              </td>
                              <td class="pagination">
                              {{ $mps->links() }}
                              </td>
                          </tr>
                  </table>
                

resources/views/layouts/mps/searchMpTable.blade.php
<a href="{{route('mps.exportsearch')}}" value="Export" ><img width="50" height="50" src="img/iconeexcel.png" alt="logo"/></a>

                  <table border="1|0">
                      <thead>
                          <tr>
                          <th colspan="1" rowspan="2">Type</th>
                            <th colspan="5">Référence Bureau d'ordre</th>
                            <th colspan="5">Référence Cabinet</th>
                            <th colspan="2"></th>
                          </tr>
                          <tr>
                          <th>N° ENVOI</th>
                          <th> Date envoie</th>
                          <th> N° Arrivé</th>
                          <th>Date arrivé</th>
                          <th>Emetteur</th>

                          <th>Date VISA</th>
                          <th>Objet</th>
                          <th>Division</th>
                          <th>Instructions</th>
                          <th>date limit</th>
                          <th>Etat</th>
                          <th>Actions</th>
                          </tr>
                      </thead>
                      <tbody>
                      @foreach ($mps as $mp)
                      <tr class="row0">
                      <td>{{$mp->type}}</td>
                      <td>{{$mp->num_envoi}}</td>
                      <td>{{$mp->date_envoie}}</td>
                      <td>{{$mp->num_arrive}}</td>
                      <td>{{$mp->date_arrive}}</td>
                      <td>{{$mp->emetteur}}</td>

                      <td>{{$mp->date_visa}}</td>
                      <td>{{$mp->objet}}</td>
                      <td>{{$mp->divisionconcernee->acronyme}}</td>
                      <td>{{$mp->instructions}}</td>
                      <td>{{$mp->date_limit}}</td>
                      <td>{{$mp->etat}}</td>

                      <td>
                      <a  href="#" title=""><input type="button" class="fa view" value="&#xf06e;"/></a>
                      <a  href="{{ route('mps.edit',$mp->id)}}" title=""><input type="button" class="fa view" value="&#xf044;"/></a>
                      {!! Form::open(['method' => 'DELETE','route' => ['mps.destroy', $mp->id],'style'=>'display:inline','onsubmit' => 'return confirmDeletemps()']) !!}
                            <input type="submit" class="fa delete" value="&#xf1f8;" />
                      {!! Form::close() !!}
                      </td>
                      </tr>
                      @endforeach                   
                      </tbody>
                  </table>
                

resources/views/layouts/mps/updatemps.blade.php
@extends('layouts.app')
@section('content')               
                     
            <h3><span class="title">Edition MP</span><span class="underlined">&nbsp;</span></h3> 
                 @if (Session::get('message'))
                <div class="success">
                    {!! Session::get('message')!!}
                </div> 
                @endif
				{{ Form::model($mp, array('route' => array('mps.update', $mp->id), 'method' => 'PUT')) }}
                <fieldset class="new_folder">
                <legend>Référence bureau d'ordre</legend>
    			<table>
                    <tr>
                    <td>{{Form::label('num_envoi', 'Numéro d envoi')}}</td>
                    <td> {{Form::number('num_envoi')}}</td>
                    <td>{{Form::label('date_envoie', 'Date envoi')}}</td>
                    <td> {{Form::date('date_envoie')}}</td>
                    </tr>
                    <tr>
                    <td>{{Form::label('num_arrive', 'Numéro d arrivée')}}</td>
                    <td> {{Form::number('num_arrive')}}</td>
                    <td>{{Form::label('date_arrive', 'Date arrivée')}}</td>
                    <td> {{Form::date('date_arrive')}}</td>
                    </tr>

                    <tr>
                    <td>{{Form::label('emetteur', 'Emetteur')}}</td>
                    <td> {{Form::text('emetteur')}}</td>
                    </tr>
                </table>    
                </fieldset>
                
                <table>
                </table>
                <fieldset class="new_folder">
                <legend>Référence Cabinet</legend>
                <table>
                <tr>
                <td>{{Form::label('date_visa', 'Date visa')}}</td>
                <td> {{Form::date('date_visa')}}</td>
                </tr>
                <tr>
                <td>{{Form::label('division_id', 'Division')}} </td>
                <td>{!! Form::select('division_id', 
                            $divisions, 
                            null,['placeholder' => 'Selectionnez Division..']) !!}</td>
                </tr>
                <tr>
                <td>{{Form::label('objet', 'Objet')}}</td>
                <td> {{Form::text('objet')}}</td>
                </tr>
                <tr>
                <td>{{Form::label('instructions', 'Instructions')}}</td>
        		<td>{{ Form::textarea('instructions') }}</td>
                </tr>
                <tr>
                <td>{{Form::label('date_limit', 'Date limite')}}</td>
                <td> {{Form::date('date_limit')}}</td>
                </tr>
                </table>
                </fieldset>

                    {{Form::label('etat', 'Etat')}} 
                    {!! Form::select('etat', 
                            ["en cours" => "en cours","traité" => "traité"], 
                            null,[]) !!}</td>

               {{Form::label('observations', 'observations')}}
        		{{ Form::textarea('observations') }}

                {{Form::submit('Valider',array('class' => 'button'))}}
				{{ Form::close() }}
              


                <div class="clear"></div>
               
                @endsection