routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::resource('dossiers','DossiersController');
Route::resource('evenements', 'EvenementsController');
Route::resource('mps','MpsController');
Route::get('/folder','DossiersController@index');
Route::post('dossier/search','DossiersController@search')->name('dossiers.search');
Route::post('mp/search','MpsController@search')->name('mps.search');
Route::get('/search','DossiersController@searchFolder');
Route::get('/statistics','DossiersController@statistics');
Auth::routes();


Route::get('/mps','MpsController@index');
Route::get('/export', 'MpsController@export')->name('mps.export');
Route::get('/exportsearch', 'MpsController@exportsearch')->name('mps.exportsearch');
Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/addFolder.blade.php
@extends('layouts.app')
@section('content')               
               <!-- block Fade in/out Message box -->
            <!--
                <h3><span class="title">Fade in/out Message box</span><span class="underlined">&nbsp;</span></h3>
                <input type="button" class="button" value="Click here to show message box" name="open_msgbox" id="open_msgbox" />
                <div class="msgbox" id="msgbox1">
                    <div class="icon"><img src="img/icons/alert.gif" alt="" title="" /></div>
                    <div class="text">
                        This block is used to display messages ( e.g. Your Page was successfully updated. )
                        <br />
                        click icon to close this message box!<br />
                    </div>
                    <div class="close"><a href="#" id="close_msgbox" title="Close message box"><img src="img/icons/icon_minus.gif" alt="" title="" /></a></div>
                    <div class="clear"></div>
                </div>
                <!-- end block Fade in/out Message box -->

           
                
                <!-- block example form -->                

                @if (Session::get('response'))
                <div class="success">
                    {!! Session::get('response')['message'] !!}
                </div> 
                <fieldset class="new_folder">
                <legend>Récapitulatif</legend>
                <div>
                <table>
                <tr>
                <td>Objet</td><td><strong>{!!Session::get('response')['data']['objet'] !!}</strong></td>
                </tr>
                <tr>
                <td>Priorité</td><td><strong>{!!Session::get('response')['data']['priorite'] !!}</strong></td>
                </tr>
                <tr>
                <td>Date début</td><td><strong>{!!Session::get('response')['data']['date_debut'] !!}</strong></td>
                </tr>
                <tr>
                <td>Date fin</td><td><strong>{!!Session::get('response')['data']['date_fin'] !!}</strong></td>
                </tr>
                <tr>
                <td>Description</td><td><strong>{!!Session::get('response')['data']['description'] !!}</strong></td>
                </tr>
                </table>
                </div>
                </fieldset>
                    @else        
            <h3><span class="title">Ajouter une instance</span><span class="underlined">&nbsp;</span></h3>         
				{{ Form::open(['route' => 'dossiers.store']) }}
                <fieldset class="new_folder">
                <legend>Veuillez remplir les champs</legend>
    				<table>
                    <tr>
                    <td>{{Form::label('objet', 'Intitulé')}}</td>
                    <td> {{Form::text('objet')}}</td>
                    <td>
                    @if ($errors->has('objet'))
                    <span class="error"> {{ $errors->first('objet') }}</span>
                    @endif
                    </td>
                    </tr>
                    <tr>
                       <td> {{ Form::hidden('division_id',Auth::user()->division_id) }} </td><td></td>
                    </tr>
                    <tr>
                        <td>{{Form::label('dvi', 'Divisions impliquées')}}</td>
                        <td>
                        {!! Form::select('di[]', 
                            $divisions, 
                            null, 
                            ['multiple' => 'multiple']) !!}
                        </select>
                        </td>
                        <td><span></span></td>
                      </tr>
                      <tr>    
                         <td> {{Form::label('type_id', 'Type du dossier')}}</td>
                          <td>
                          {!! Form::select('type_id', 
                            $types, 
                            null,[]) !!}
                          </td>
                          <td>
                          @if ($errors->has('type_id'))
                          <span class="error">{{ $errors->first('type_id') }}</span>
                          @endif
                          </td>
                    </tr>
                       <tr>  
                       <td> 
                          {{Form::label('priorite', 'Priorité')}}
                        </td>  
                        <td>
                        {{Form::select('priorite', array('Critique' => 'Critique', 'Elevé' => 'Elevé','Normal' => 'Normal'))}}
                        </td>
                        <td>
                        @if ($errors->has('priorite'))
                        <span class="error">{{ $errors->first('priorite') }}</span>
                        @endif
                        </td>
                        </tr>
                        <tr>
                        <td>
                        {{Form::label('date_debut', 'Date début')}}
                        {{Form::date('date_debut', \Carbon\Carbon::now())}}
                        </td>
                        <td>
                        {{Form::label('date_fin', 'Date Fin')}}
                        {{Form::date('date_fin', \Carbon\Carbon::now())}}
                        </td>
                        <td>
                          @if ($errors->has('date_fin'))
                          <span class="error">{{ $errors->first('date_fin') }}</span>
                          @endif
                          </td>
                        </tr>
                        <tr>
                        <td>
        				{{Form::label('description', 'Description')}}
                        </td> 
                        <td>
        				{{ Form::textarea('description') }}
                        </td>
                        <td>
                        @if ($errors->has('description'))
                        <span class="error">{{ $errors->first('description') }}</span>
                        @endif
                        </td>
        				</tr>
                        <tr>
                        <td></td>
                        <td>
                        {{Form::submit('Valider',array('class' => 'button'))}}
                        </td>
                        <td></td>
                        </tr>
        				
                        </table>
                </fieldset>
				{{ Form::close() }}
                <!-- end block example form -->


                <div class="clear"></div>
                @endif
                @endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <link rel="shortcut icon" type="image/x-icon" href="{{ asset('/img/icons/logo_interieur.ico')}}" />
  <title>Province Fquih ben Saleh</title>
  
  
  <link type="text/css" href="{{ asset('/css/style.css') }}" rel="stylesheet" />
  <link rel="stylesheet" href="{{ asset('/font-awesome/css/font-awesome.min.css')}}" />

  <!--[if lte IE 6]>
    <link type="text/css" href="./css/style_ie6.css" rel="stylesheet" />
  <![endif]-->
  <script type="text/javascript" src="{{ asset('/js/jquery-1.11.1.min.js')}}"></script> 
  <script type="text/javascript" src="{{ asset('/js/script.js')}}"></script>
<script type="text/javascript" src="{{ asset('/js/jquery.canvasjs.min.js')}}"></script>
</head>

<body>
<div id="page">

  <!-- header -->
  <div id="header">
      <div id="logo"><h1><a href="#" title="Your site name"><img style="height:100px" src="{{ asset('/img/logo_interieur.png')}}" alt="logo"/></a></h1></div>
      <div id="div_header"><img src="{{ asset('img/header.png')}}" /></div>
      <div id="quicklink"><i class="fa fa-user fa-lg" aria-hidden="true"></i>
 | <a href="{{ route('login') }}">{{ Auth::user()->name }}</a> | <a href="{{ url('/logout') }}"
    onclick="event.preventDefault();
             document.getElementById('logout-form').submit();" title="logout"><i class="fa fa-power-off fa-lg" aria-hidden="true"></i>
</a>
<form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
    {{ csrf_field() }}
</form>
</div>
  </div>
  <!-- end header -->


  <!-- main menu -->
  <div id="mainmenu">
      <ul>
      <!--
          <li class="item"><a href="{{url('/folder')}}"><span class="item-icon"><i class="fa fa-folder fa-2x"></i></span><span class="item-text">DOSSIERS</span></a></li>
          <li class="item"><a href="{{ route('dossiers.create') }}"><span class="item-icon"><i class="fa fa-folder-open fa-2x"></i></span><span class="item-text">NOUVEAU</span></a></li>
          <li class="item"><a href="{{ url('/search') }}"><span class="item-icon"><i class="fa fa-search fa-2x"></i></span><span class="item-text">CHERCHER</span></a></li>

          @if (Auth::user()->isSuperAdmin())
          <li class="item"><a href="{{ url('/statistics') }}"><span class="item-icon"><i class="fa fa-pie-chart fa-2x"></i></span><span class="item-text">STATISTIQUES</span></a></li>
          @endif
          -->
          <li class="item"><a href="{{ url('/mps') }}"><span class="item-icon"><i class="fa fa-edit fa-2x"></i></span><span class="item-text">INSTRUCTIONS</span></a></li>
          <li class="item"><a href="{{ route('mps.create') }}"><span class="item-icon"><i class="fa fa-folder-open fa-2x"></i></span><span class="item-text">NOUVEAU</span></a></li>
      </ul>
  </div>
  <!-- end mainmenu -->
<!--
    <div id="submenu">
        <ul>
            <li><a href="#" title="">Manager</a></li>
            <li><a href="#" title="" class="active">Advanced search</a></li>
            <li><a href="#" title="">Options</a></li>
            <li><a href="#" title="">Daily Reports</a></li>
        </ul>
        <div class="clear"></div>
    </div>
-->
  <!-- content -->
      <div id="content">
          @yield('content')              
      </div>
      <!-- end div content -->

  <!-- Footer -->
  <div id="footer">
      <ul>
          <li>&copy;2018 <a href="#" title="">Gestion des MPs</a>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
          <li>Powered by <a href="#" title="">DSIC FBS</a></li>
      </ul>
  </div>

</div>
<!-- end div page -->
</body>

</html>

resources/views/layouts/detail_folder.blade.php
@extends('layouts.app')
@section('content')
<script type="text/javascript">
$(function() {
  
  // contact form animations
  $('#addevenement').click(function() {
    $('#evenementForm').fadeToggle();
  })
  $(document).mouseup(function (e) {
    var container = $("#evenementForm");

    if (!container.is(e.target) // if the target of the click isn't the container...
        && container.has(e.target).length === 0) // ... nor a descendant of the container
    {
        container.fadeOut();
    }
  });
  
});
</script>
<div id="c-mask" class="c-mask is-active"></div>
                <fieldset>
                <legend>Détails dossier</legend>
    				<p>
            <table>
            <tr>
            <td>
        				<label>Objet</label>
            </td>
            <td>
        				<input name="dname" value="{{$dossier->objet}}" type="text" size="30" disabled="true"/>
            </td>    
            </tr>   
            <tr>
            <td><label>Division concernée</label></td>
            <td> @foreach($divisionimpliques as $division) 
                <input name="{{$division->intitule}}" value="{{$division->acronyme}}" type="text" size="30" />
                @endforeach</td>
            </tr> 

            <tr>
            <td><label>Date début</label></td>
            <td><input name="ddebut" value="{{$dossier->date_debut}}" type="text" size="30" disabled="true"/></td>
            </tr>

            <tr>
            <td><label>Date Fin</label></td>
            <td><input name="dfin" value="{{$dossier->date_fin}}" type="text" size="30" disabled="true"/></td>
            </tr>
                
            <tr>
            <td>	<label>Description</label></td>
            <td>	<textarea rows="5" cols="5" value="">{{$dossier->description}}</textarea></td>
            </tr>    
                </table>
    				</p>
            <br />
                </fieldset>
                <!--  Liste événement -->
                <fieldset>
                <legend>Historique des évenements</legend>
                <a class="add fa" id="addevenement" href="#" title="">&#xf067 Ajouter un évenement</a>
                <div class="evenementsbox">
                
                @if (count($evenements) === 0)
                Aucun évenement
                @else
                  <table style="width:70%">
                      <thead>
                          <tr>                    
                            <th width="20%">objet</th>
                            <th width="30%">Date d'évenement</th>
                            <th width="50%">Remarques</th>
                          </tr>
                          @foreach($evenements as $evenement) 
                          <tr>                        
                            <td>{{$evenement->intitule}}</td>
                            <td>{{$evenement->created_at}}</td>
                            <td>{{$evenement->remarques}}</td>
                          </tr>
                          @endforeach
                      </thead>
                      <tbody>                          
                      </tbody>
                  </table>
                  @endif
                </div>
</fieldset>

<!-- popup evenement -->

<div id="evenementForm">  
  {{ Form::open(['route' => 'evenements.store']) }}
    <table>
    <tr>
    <td>{{Form::label('intitule', 'Intitulé')}}</td>
    <td>{{Form::text('intitule')}}</td>
    <td> @if ($errors->has('type_id'))
      <span class="error">{{ $errors->first('intitule') }}</span>
     @endif
     </td>
    </tr>
    <tr>
    <td>{{Form::label('remarques', 'Remarques')}}</td>
    <td>{{ Form::textarea('remarques') }}</td>
    <td>
    <td> @if ($errors->has('reamrques'))
      <span class="error">{{ $errors->first('remarques') }}</span>
     @endif
     </td>
    </td>
    </tr>
    <tr>
      <td> {{ Form::hidden('dossier_id',$dossier->id) }} </td>
      
    </tr>
    </table>
    {{Form::submit('Valider',array('class' => 'button'))}}
    {{ Form::close() }}
</div>

@endsection

resources/views/layouts/editFolder.blade.php
@extends('layouts.app')
@section('content')  
                    
            <h3><span class="title">Ajouter une instance</span><span class="underlined">&nbsp;</span></h3>  
            @if (Session::has('message'))
                <div class="success">
                    {!! Session::get('message') !!}
                </div>
            @endif       
            {{ Form::model($dossier, array('route' => array('dossiers.update', $dossier->id), 'method' => 'PUT')) }}
                <fieldset class="new_folder">
                <legend>Veuillez remplir les champs</legend>
    				<table>
                    <tr>
                    <td>{{Form::label('objet', 'Intitulé')}}</td>
                    <td> {{Form::text('objet')}}</td>
                    <td>
                    @if ($errors->has('objet'))
                    <span class="error"> {{ $errors->first('objet') }}</span>
                    @endif
                    </td>
                    </tr>
                    <tr>
                       <td> {{ Form::hidden('division_id',Auth::user()->division_id) }} </td><td></td>
                    </tr>
                    <tr>
                        <td>{{Form::label('dvi', 'Divisions impliquées')}}</td>
                        <td>
                        {!! Form::select('di[]', 
                            $divisions, 
                            null, 
                            ['multiple' => 'multiple']) !!}
                        </td>
                        <td><span></span></td>
                      </tr>
                      <tr>    
                         <td> {{Form::label('type_id', 'Type du dossier')}}</td>
                          <td>
                          {!! Form::select('type_id', 
                            $types, 
                            null,[]) !!}
                          </td>
                          <td>
                          @if ($errors->has('type_id'))
                          <span class="error">{{ $errors->first('type_id') }}</span>
                          @endif
                          </td>
                    </tr>
                       <tr>  
                       <td> 
                          {{Form::label('priorite', 'Priorité')}}
                        </td>  
                        <td>
                        {{Form::select('priorite', array('Critique' => 'Critique', 'Elevé' => 'Elevé'))}}
                        </td>
                        <td>
                        @if ($errors->has('priorite'))
                        <span class="error">{{ $errors->first('priorite') }}</span>
                        @endif
                        </td>
                        </tr>

                        <tr>  
                       <td> 
                          {{Form::label('Etat', 'Etat dossier')}}
                        </td>  
                        <td>
                        {!! Form::select('etat_id', 
                            $etats, 
                            null,[]) !!}
                        </td>
                        <td>
                        @if ($errors->has('etat_id'))
                        <span class="error">{{ $errors->first('etat_id') }}</span>
                        @endif
                        </td>
                        </tr>
                        <tr>
                        <td>
                        {{Form::label('date_debut', 'Date début')}}
                        {{Form::date('date_debut')}}
                        </td>
                        <td>
                        {{Form::label('date_fin', 'Date Fin')}}
                        {{Form::date('date_fin')}}
                        </td>
                        <td>
                          @if ($errors->has('date_fin'))
                          <span class="error">{{ $errors->first('date_fin') }}</span>
                          @endif
                          </td>
                        </tr>
                        <tr>
                        <td>
        				{{Form::label('description', 'Description')}}
                        </td> 
                        <td>
        				{{ Form::textarea('description') }}
                        </td>
                        <td>
                        @if ($errors->has('description'))
                        <span class="error">{{ $errors->first('description') }}</span>
                        @endif
                        </td>
        				</tr>
                        <tr>
                        <td></td>
                        <td>
                        {{Form::submit('Valider',array('class' => 'button'))}}
                        </td>
                        <td></td>
                        </tr>
        				
                        </table>
                </fieldset>
				{{ Form::close() }}
                <!-- end block example form -->
                <div class="clear"></div>           
                @endsection

resources/views/layouts/index.blade.php
@extends('layouts.app')
@section('content')
<h3><span class="title">Les dossiers en instance</span><span class="underlined">&nbsp;</span></h3>
                
                <div class="tablebox">
                  <table border="1|0">
                      <thead>
                          <tr>
                            <th>Intitulé</th>
                            <th>Division concernée</th>
                            <th>Divisions impliquées</th>
                            <th>Priorité</th>
                            <th>Etat</th>
                            <th>Description</th>
                            <th class="action">Action</th>
                          </tr>
                      </thead>
                      <tbody>
                      @foreach ($dossiers as $dossier)
                      <tr class="row0">
                            <td>{{$dossier->objet}}</td>
                            <td>{{$dossier->divisionconcernee->acronyme}}</td>
                            <td>
                            @if(count($dossier->divisionsimpliquees)===0)
                            Aucune division impliquée
                            @else
                            @foreach ($dossier->divisionsimpliquees as $division)
                            <span>{{ $division->acronyme }}</span>
                            @endforeach
                            @endif
                            </td>
                            <td>{{$dossier->priorite}}</td>                          
                            <td>{{$dossier->etat->intitule}}</td>
                            <td>{{$dossier->description}}</td>
                            <td class="action">
                            <a  href="{{ route('dossiers.show',$dossier->id)}}" title=""><input type="button" class="fa view" value="&#xf06e;"/></a>
                            <a href="{{ route('dossiers.edit',$dossier->id)}}" title=""><input type="button" class="fa edit" value="&#xf044;"/></a>
                            {!! Form::open(['method' => 'DELETE','route' => ['dossiers.destroy', $dossier->id],'style'=>'display:inline','onsubmit' => 'return confirmDelete()']) !!}
                            <input type="submit" class="fa delete" value="&#xf1f8;" />
                            {!! Form::close() !!}
                                   
                          </td>
                          </tr>     
                        @endforeach                                      
                      </tbody>
                  </table>
                  <table>
                          <tr>
                              <td>                       
                              <b> Total: {{$dossiers->total()}} dossiers trouvés</b>
                              </td>
                              <td class="pagination">
                              {{ $dossiers->links() }}
                              </td>
                          </tr>
                  </table>
                </div>
                <div class="clear"></div>
                @endsection

resources/views/layouts/search.blade.php
@extends('layouts.app')
@section('content')
<h3><span class="title">Trouver un dossier</span><span class="underlined">&nbsp;</span></h3>
            {{ Form::open(['route' => 'dossiers.search']) }}
                <fieldset>
                <legend>Critères de recherche</legend>
    				<table>
                    <tr>  
                    <td>              
                   {{Form::label('mots', 'Mots clé')}}
                   </td>
                   <td>
                    {{Form::text('mots')}}
                  </td>

                  <td>
                  @if (Auth::user()->isSuperAdmin())
                  {{Form::label('division', 'division')}}
                  </td>
                  <td>    
                  {!! Form::select('division_id', 
                            $divisions, 
                            null,['placeholder' => 'Selectionnez Division..']) !!}
                    @endif
                   </td> 
                  </tr>
                  <tr>
                  <td>
                  {{Form::label('type_id', 'Type dossier')}}
                  </td>
                  <td>    
                  {!! Form::select('type_id', 
                            $types, 
                            null,['placeholder' => 'Selectionnez Type..']) !!}
                   </td>     
                     </tr>   
                        <tr>
                        <td>
                        {{Form::label('date_debut', 'Date début')}}
                        </td>
                        <td>
                        {{Form::date('date_debut')}}
                        </td>
                        <td>
                        {{Form::label('date_fin', 'Date Fin')}}
                        </td>
                        <td>
                        {{Form::date('date_fin')}}
                        </td>
                        </tr>
        				<tr>
                        <td>
                        {{Form::submit('Valider',array('class' => 'button'))}}
                        </td>
                        </tr>
    				</table>
                  
                </fieldset>
                    {{ Form::close() }}
                <!-- end block example form -->


                <div class="clear"></div>
            
                <h3><span class="title">Résultat de la recherche</span><span class="underlined">&nbsp;</span></h3>
                <div class="tablebox">
                  <table>
                      <thead>
                      <tr>
                            <th>Intitulé</th>
                            <th>Type</th>
                            <th>Divisions impliquées</th>
                            <th>Priorité</th>
                            <th>Etat</th>
                            <th>Description</th>
                            <th class="action">Action</th>
                          </tr>
                      </thead>
                      <tbody>
                      @if (Session::has('response'))
                      @if (count(Session::get('response'))===0)
                      <tr><td>Aucun élément trouvé</td></tr>
                      @else
                      @foreach (Session::get('response') as $dossier)
                      <tr class="row0">
                            <td>{{$dossier->objet}}</td>
                            <td>{{$dossier->type->intitule}}</td>
                            <td>
                            @if(count($dossier->divisionsimpliquees)===0)
                            Aucune division impliquée
                            @else
                            @foreach ($dossier->divisionsimpliquees as $division)
                            <span>{{ $division->acronyme }}</span>
                            @endforeach
                            @endif
                            </td>
                            <td>{{$dossier->priorite}}</td>                          
                            <td>{{$dossier->etat->intitule}}</td>
                            <td>{{$dossier->description}}</td>
                            <td class="action">
                            <a  href="{{ route('dossiers.show',$dossier->id)}}" title=""><input type="button" class="fa view" value="&#xf06e;"/></a>
                            <a href="{{ route('dossiers.edit',$dossier->id)}}" title=""><input type="button" class="fa edit" value="&#xf044;"/></a>
                            {!! Form::open(['method' => 'DELETE','route' => ['dossiers.destroy', $dossier->id],'style'=>'display:inline']) !!}
                            <input type="submit" class="fa delete" value="&#xf1f8;" />
                            {!! Form::close() !!}
                                   
                          </td>
                          </tr>     
                      @endforeach
                      @endif                        
                      </tbody>
                  </table>
                  <table>
                          <tr>
                              <td>                       
                              <b> Total: {{Session::get('response')->total()}} dossiers trouvés</b>
                              </td>
                              <td class="pagination">
                              {{ Session::get('response')->links() }}
                              </td>
                          </tr>
                  </table>
                  @endif 
                </div>
                <!-- end block example table -->
@endsection
              

resources/views/layouts/statistics.blade.php
@extends('layouts.app')
@section('content')
<script type="text/javascript">
    window.onload = function() {
    var options = {
        exportEnabled: true,
        animationEnabled: true,
        title:{
            text: "Dossiers"
        },
        legend:{
            horizontalAlign: "right",
            verticalAlign: "center"
        },
        data: [{
            type: "pie",
            showInLegend: true,
            toolTipContent: "<b>{name}</b>: ${y} (#percent%)",
            indexLabel: "{name}",
            legendText: "{name} (#percent%)",
            indexLabelPlacement: "inside",
            dataPoints: [              
                @foreach ($etatdossiers as $state)
            { y: {{$state->count}}, name: "{{$state->intitule}}" },
            @endforeach
            ]
        }]
    };
    $("#chartContainer").CanvasJSChart(options);

    var optionsGraphe = {
	animationEnabled: true,
	title: {
		text: "Dossier par division"
	},
	axisY: {
		title: "Nombre de dossiers",
		suffix: "",
		includeZero: false
	},
	axisX: {
		title: "Divisions"
	},
	data: [{
		type: "column",
		yValueFormatString: "#,##0.0#"%"",
		dataPoints: [
            @foreach ($divisions as $division)
            { label: "{{$division->acronyme}}", y: {{$division->count}} },
            @endforeach	
		]
	}]
};
$("#GrapheContainer").CanvasJSChart(optionsGraphe);
    
    }
    
    </script>            
            <div id="chartContainer" style="height: 370px; width: 40%;display: inline-block;"></div>
           
            <div id="GrapheContainer" style="height: 370px; width: 40%;display: inline-block;"></div>
      <!-- end div content -->
@endsection